# Generated by Django 3.0.3 on 2020-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200608_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('payment', models.CharField(max_length=40, verbose_name='Meio de Pagamento')),
                ('products', models.ManyToManyField(to='produtos.Product')),
            ],
        ),
    ]
